/*
 * $FILE: devices.c
 *
 *
 * $VERSION$
 *
 * Authors: Miguel Masmano <mmasmano@ai2.upv.es>
 *
 * $LICENSE:
 * (c) Universidad Politecnica de Valencia. All rights reserved.
 *     Read LICENSE.txt file for the license.terms.
 */

#include "xmcparser.h"
#include "hm.h"
#include "constraints.h"
#include <string.h>
#include <stdio.h>

#define TOSTR(x) #x

char *hmEvents[XM_HM_MAX_EVENTS]={
    [XM_HM_EV_INTERNAL_ERROR]                = TOSTR(XM_HM_EV_INTERNAL_ERROR),
    [XM_HM_EV_UNEXPECTED_TRAP]               = TOSTR(XM_HM_EV_UNEXPECTED_TRAP),
    [XM_HM_EV_PARTITION_UNRECOVERABLE]       = TOSTR(XM_HM_EV_PARTITION_UNRECOVERABLE),
    [XM_HM_EV_PARTITION_ERROR]               = TOSTR(XM_HM_EV_PARTITION_ERROR),
    [XM_HM_EV_PARTITION_INTEGRITY]           = TOSTR(XM_HM_EV_PARTITION_INTEGRITY),
    [XM_HM_EV_MEM_PROTECTION]                = TOSTR(XM_HM_EV_MEM_PROTECTION),
    [XM_HM_EV_OVERRUN]                       = TOSTR(XM_HM_EV_OVERRUN),
    [XM_HM_EV_SCHED_ERROR]                   = TOSTR(XM_HM_EV_SCHED_ERROR),
    [XM_HM_EV_WATCHDOG_TIMER]                = TOSTR(XM_HM_EV_WATCHDOG_TIMER),
    [XM_HM_EV_INCOMPATIBLE_INTERFACE]        = TOSTR(XM_HM_EV_INCOMPATIBLE_INTERFACE),

#ifdef ia32
    [XM_HM_EV_IA32_DIVIDE_EXCEPTION]         = TOSTR(XM_HM_EV_IA32_DIVIDE_EXCEPTION),
    [XM_HM_EV_IA32_DEBUGGER_EXCEPTION]       = TOSTR(XM_HM_EV_IA32_DEBUGGER_EXCEPTION),
    [XM_HM_EV_IA32_NMI_EXCEPTION]            = TOSTR(XM_HM_EV_IA32_NMI_EXCEPTION),
    [XM_HM_EV_IA32_BREAKPOINT_EXCEPTION]     = TOSTR(XM_HM_EV_IA32_BREAKPOINT_EXCEPTION),
    [XM_HM_EV_IA32_OVERFLOW_EXCEPTION]       = TOSTR(XM_HM_EV_IA32_OVERFLOW_EXCEPTION),
    [XM_HM_EV_IA32_BOUNDS_EXCEPTION]         = TOSTR(XM_HM_EV_IA32_BOUNDS_EXCEPTION),
    [XM_HM_EV_IA32_INVALID_OPCODE]           = TOSTR(XM_HM_EV_IA32_INVALID_OPCODE),
    [XM_HM_EV_IA32_COPROCESOR_UNAVAILABLE]   = TOSTR(XM_HM_EV_IA32_COPROCESOR_UNAVAILABLE),
    [XM_HM_EV_IA32_DOUBLE_FAULT]             = TOSTR(XM_HM_EV_IA32_DOUBLE_FAULT),
    [XM_HM_EV_IA32_COPROCESSOR_OVERRUN]      = TOSTR(XM_HM_EV_IA32_COPROCESSOR_OVERRUN),
    [XM_HM_EV_IA32_INVALID_TSS]              = TOSTR(XM_HM_EV_IA32_INVALID_TSS),
    [XM_HM_EV_IA32_SEGMENT_NOT_PRESENT]      = TOSTR(XM_HM_EV_IA32_SEGMENT_NOT_PRESENT),
    [XM_HM_EV_IA32_STACK_FAULT]              = TOSTR(XM_HM_EV_IA32_STACK_FAULT),
    [XM_HM_EV_IA32_GENERAL_PROTECTION_FAULT] = TOSTR(XM_HM_EV_IA32_GENERAL_PROTECTION_FAULT),
    [XM_HM_EV_IA32_PAGE_FAULT]               = TOSTR(XM_HM_EV_IA32_PAGE_FAULT),
    [XM_HM_EV_IA32_RESERVED]                 = TOSTR(XM_HM_EV_IA32_RESERVED),
    [XM_HM_EV_IA32_MATH_FAULT]               = TOSTR(XM_HM_EV_IA32_MATH_FAULT),
    [XM_HM_EV_IA32_ALIGNMENT_CHECK]          = TOSTR(XM_HM_EV_IA32_ALIGNMENT_CHECK),
    [XM_HM_EV_IA32_MACHINE_CHECK]            = TOSTR(XM_HM_EV_IA32_MACHINE_CHECK),
    [XM_HM_EV_IA32_FLOATING_POINT_EXCEPTION] = TOSTR(XM_HM_EV_IA32_FLOATING_POINT_EXCEPTION),
#endif
};

#define TOBIT(x) (1<<x)

int hmPartEventsAndActions[XM_HM_MAX_EVENTS]= {
    [XM_HM_EV_INTERNAL_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_UNEXPECTED_TRAP]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_PARTITION_UNRECOVERABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_PARTITION_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_PARTITION_INTEGRITY]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_MEM_PROTECTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_SCHED_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_WATCHDOG_TIMER]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),
    
    [XM_HM_EV_INCOMPATIBLE_INTERFACE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

#ifdef ia32
    [XM_HM_EV_IA32_DIVIDE_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_DEBUGGER_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_NMI_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_BREAKPOINT_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_OVERFLOW_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_BOUNDS_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_INVALID_OPCODE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_COPROCESOR_UNAVAILABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_DOUBLE_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_COPROCESSOR_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_INVALID_TSS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_SEGMENT_NOT_PRESENT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_STACK_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_GENERAL_PROTECTION_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_PAGE_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_RESERVED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_MATH_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_ALIGNMENT_CHECK]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_MACHINE_CHECK]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_FLOATING_POINT_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),
#endif
};

int hmHpvEventsAndActions[XM_HM_MAX_EVENTS]= {
    [XM_HM_EV_INTERNAL_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_UNEXPECTED_TRAP]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_PARTITION_UNRECOVERABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_PARTITION_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_PARTITION_INTEGRITY]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_MEM_PROTECTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_SCHED_ERROR]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_WATCHDOG_TIMER]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

    [XM_HM_EV_INCOMPATIBLE_INTERFACE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT),

#ifdef ia32
    [XM_HM_EV_IA32_DIVIDE_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_DEBUGGER_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_NMI_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_BREAKPOINT_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_OVERFLOW_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_BOUNDS_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_INVALID_OPCODE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_COPROCESOR_UNAVAILABLE]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_DOUBLE_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_COPROCESSOR_OVERRUN]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_INVALID_TSS]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_SEGMENT_NOT_PRESENT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_STACK_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_GENERAL_PROTECTION_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_PAGE_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_RESERVED]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_MATH_FAULT]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_ALIGNMENT_CHECK]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_MACHINE_CHECK]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),

    [XM_HM_EV_IA32_FLOATING_POINT_EXCEPTION]=TOBIT(XM_HM_AC_IGNORE)|TOBIT(XM_HM_AC_SHUTDOWN)|TOBIT(XM_HM_AC_COLD_RESET)|TOBIT(XM_HM_AC_WARM_RESET)|TOBIT(XM_HM_AC_SUSPEND)|TOBIT(XM_HM_AC_HALT)|TOBIT(XM_HM_AC_PROPAGATE),
#endif
};

char *hmActions[MAX_HM_ACTIONS]={
    [XM_HM_AC_IGNORE]     = TOSTR(XM_HM_AC_IGNORE),
    [XM_HM_AC_SHUTDOWN]   = TOSTR(XM_HM_AC_SHUTDOWN),
    [XM_HM_AC_COLD_RESET] = TOSTR(XM_HM_AC_COLD_RESET),
    [XM_HM_AC_WARM_RESET] = TOSTR(XM_HM_AC_WARM_RESET),
    [XM_HM_AC_SUSPEND]    = TOSTR(XM_HM_AC_SUSPEND),
    [XM_HM_AC_HALT]       = TOSTR(XM_HM_AC_HALT),
    [XM_HM_AC_PROPAGATE]  = TOSTR(XM_HM_AC_PROPAGATE),
};

char *hmLog[]= {
    [XM_HM_LOG_DISABLED] = TOSTR(XM_HM_LOG_DISABLED),
    [XM_HM_LOG_ENABLED]  = TOSTR(XM_HM_LOG_ENABLED),
};

static struct xmcHmSlot defaultPartHmTab[XM_HM_MAX_EVENTS]={
    [XM_HM_EV_INTERNAL_ERROR]          = {.action = XM_HM_AC_WARM_RESET, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_UNEXPECTED_TRAP]         = {.action = XM_HM_AC_IGNORE, .log     = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_UNRECOVERABLE] = {.action = XM_HM_AC_HALT, .log       = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_ERROR]         = {.action = XM_HM_AC_HALT, .log       = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_INTEGRITY]     = {.action = XM_HM_AC_HALT, .log       = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_MEM_PROTECTION]          = {.action = XM_HM_AC_SUSPEND, .log    = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_OVERRUN]                 = {.action = XM_HM_AC_IGNORE, .log     = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SCHED_ERROR]             = {.action = XM_HM_AC_IGNORE, .log     = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_WATCHDOG_TIMER]          = {.action = XM_HM_AC_HALT, .log       = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_INCOMPATIBLE_INTERFACE]  = {.action = XM_HM_AC_IGNORE, .log     = XM_HM_LOG_ENABLED, },

#ifdef ia32
    [XM_HM_EV_IA32_DIVIDE_EXCEPTION]         = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_DEBUGGER_EXCEPTION]       = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_NMI_EXCEPTION]            = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_BREAKPOINT_EXCEPTION]     = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_OVERFLOW_EXCEPTION]       = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_BOUNDS_EXCEPTION]         = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_INVALID_OPCODE]           = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_COPROCESOR_UNAVAILABLE]   = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_DOUBLE_FAULT]             = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_COPROCESSOR_OVERRUN]      = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_INVALID_TSS]              = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_SEGMENT_NOT_PRESENT]      = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_STACK_FAULT]              = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_GENERAL_PROTECTION_FAULT] = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_PAGE_FAULT]               = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_RESERVED]                 = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_MATH_FAULT]               = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_ALIGNMENT_CHECK]          = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_MACHINE_CHECK]            = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
    [XM_HM_EV_IA32_FLOATING_POINT_EXCEPTION] = {.action = XM_HM_AC_PROPAGATE, .log = XM_HM_LOG_DISABLED, },
#endif
};

static struct xmcHmSlot defaultHpvHmTab[XM_HM_MAX_EVENTS]={
    [XM_HM_EV_INTERNAL_ERROR]          = {.action = XM_HM_AC_HALT, .log    = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_UNEXPECTED_TRAP]         = {.action = XM_HM_AC_HALT, .log    = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_UNRECOVERABLE] = {.action = XM_HM_AC_HALT, .log    = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_ERROR]         = {.action = XM_HM_AC_HALT, .log    = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_PARTITION_INTEGRITY]     = {.action = XM_HM_AC_HALT, .log    = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_MEM_PROTECTION]          = {.action = XM_HM_AC_HALT, .log    = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_OVERRUN]                 = {.action = XM_HM_AC_IGNORE, .log  = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_SCHED_ERROR]             = {.action = XM_HM_AC_IGNORE, .log  = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_WATCHDOG_TIMER]          = {.action = XM_HM_AC_HALT, .log    = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_INCOMPATIBLE_INTERFACE]  = {.action = XM_HM_AC_HALT, .log    = XM_HM_LOG_ENABLED, },

#ifdef ia32
    [XM_HM_EV_IA32_DIVIDE_EXCEPTION]         = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_DEBUGGER_EXCEPTION]       = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_NMI_EXCEPTION]            = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_BREAKPOINT_EXCEPTION]     = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_OVERFLOW_EXCEPTION]       = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_BOUNDS_EXCEPTION]         = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_INVALID_OPCODE]           = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_COPROCESOR_UNAVAILABLE]   = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_DOUBLE_FAULT]             = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_COPROCESSOR_OVERRUN]      = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_INVALID_TSS]              = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_SEGMENT_NOT_PRESENT]      = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_STACK_FAULT]              = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_GENERAL_PROTECTION_FAULT] = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_PAGE_FAULT]               = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_RESERVED]                 = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_MATH_FAULT]               = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_ALIGNMENT_CHECK]          = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_MACHINE_CHECK]            = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
    [XM_HM_EV_IA32_FLOATING_POINT_EXCEPTION] = {.action = XM_HM_AC_HALT, .log = XM_HM_LOG_ENABLED, },
#endif
};

static int HmHpvAllowedAct(struct xmc *xmcTab) {
    int i;
    for (i=0; i<XM_HM_MAX_EVENTS; i++) {
	if (!(hmPartEventsAndActions[i]&TOBIT(xmcTab->hpv.hmTab[i].action))) {
	    fprintf(stderr, "Event \"%s\" does not allow the action \"%s\"\n", hmEvents[i], hmActions[xmcTab->hpv.hmTab[i].action]);
	    return -1;
	}
    }
    return 0;
}

static int HmPartAllowedAct(struct xmc *xmcTab) {
    int e, i;
    for (e=0; e<xmcTab->noPartitions; e++) {
	for (i=0; i<XM_HM_MAX_EVENTS; i++) {
	    if (!(hmPartEventsAndActions[i]&TOBIT(partitionTab[e].hmTab[i].action))) {
		fprintf(stderr, "Event \"%s\" does not allow the action \"%s\"\n", hmEvents[i], hmActions[partitionTab[e].hmTab[i].action]);
		return -1;
	    }
	}
    }
    return 0;
}

void InitHm(void){
    AddConstraint("HM XM allowed actions", HmHpvAllowedAct);  
    AddConstraint("HM partition allowed actions", HmPartAllowedAct); 
}

void SetDefPartHmTab(struct xmcHmSlot *hmTab) {
    memcpy(hmTab, defaultPartHmTab, sizeof(struct xmcHmSlot)*XM_HM_MAX_EVENTS);
}

void SetDefHpvHmTab(struct xmcHmSlot *hmTab) {
    memcpy(hmTab, defaultHpvHmTab, sizeof(struct xmcHmSlot)*XM_HM_MAX_EVENTS);
}
